apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-c-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - monitoring-app
  selector:
    matchLabels:
      app: service-c
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
