apiVersion: v1
kind: Service
metadata:
  name: service-b-svc
  namespace: monitoring-app
  labels:
    app: service-b
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      name: metrics
  selector:
    app: service-b
