apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: monitoring-app
data:
  NODE_ENV: 'production'
  REDIS_HOST: 'redis'
  REDIS_PORT: '6379'
  SERVICE_A_PORT: '3000'
  SERVICE_B_PORT: '3001'
  SERVICE_C_PORT: '3002'
